Repository antvis/antvis.github.io, pull requests merged in 2019-11, with the labels that each got.

#24 feat: redirect old urls
  gatsby-config.js
  package.json
Labels: PR: unreviewed, enhancement

#23 Dev
  package-lock.json
  package.json
  site/components/aboutUsBannerPage/aboutUsBannerPage.module.less
  site/components/aboutUsBannerPage/aboutUsBannerPage.tsx
  site/components/advantageCard/advantageCard.module.less
  site/components/advantageCard/advantageCard.tsx
  site/components/advantagesPage/advantagesPage.module.less
  site/components/advantagesPage/advantagesPage.tsx
  site/components/bannerPage/bannerPage.module.less
  site/components/bannerPage/bannerPage.tsx
  site/components/bannerSVG/bannerSVG.module.less
  site/components/bannerSVG/bannerSVG.tsx
  site/components/companiesPage/companiesPage.module.less
  site/components/companiesPage/companiesPage.tsx
  site/components/contributorCard/contributorCard.module.less
  site/components/contributorCard/contributorCard.tsx
  site/components/contributorsPage/contributorsPage.module.less
  site/components/contributorsPage/contributorsPage.tsx
  site/components/decisionTreePage/decisionTreePage.module.less
  site/components/decisionTreePage/decisionTreePage.tsx
  site/components/describePage/describePage.module.less
  site/components/describePage/describePage.tsx
  site/components/feedbackPage/feedbackPage.module.less
  site/components/feedbackPage/feedbackPage.tsx
  site/components/joinUsPage/joinUsPage.module.less
  site/components/joinUsPage/joinUsPage.tsx
  site/components/notification/notification.module.less
  site/components/notification/notification.tsx
  site/components/productsPage/productsPage.module.less
  site/components/productsPage/productsPage.tsx
  site/components/quoteCard/quoteCard.module.less
  site/components/quoteCard/quoteCard.tsx
  site/components/quotesPage/quotesPage.module.less
  site/components/quotesPage/quotesPage.tsx
  site/components/resourceCard/resourceCard.module.less
  site/components/resourceCard/resourceCard.tsx
  site/components/resourcesPage/resourcesPage.module.less
  site/components/resourcesPage/resourcesPage.tsx
  site/data/contributors.tsx
  site/data/decision-tree-chartype.json
  site/data/decision-tree-datatype.json
  site/data/decision-tree-goal.json
  site/data/historyContributors.tsx
  site/locale.json
  site/pages/about.en.tsx
  site/pages/about.zh.tsx
  site/pages/index.less
  site/pages/index.zh.tsx
Labels: PR: unreviewed

#26 Dev
  site/components/bannerSVG/bannerSVG.module.less
  site/components/quoteCard/quoteCard.module.less
Labels: PR: unreviewed

#39 fix: external link 404 problem
  gatsby-browser.js
  package.json
Labels: PR: unreviewed, bug

#40 chore: compress image
  site/components/bannerSVG/bannerSVG.tsx
Labels: PR: unreviewed, chore

#45 fix English document title
  site/locale.json
Labels: PR: unreviewed

#47 fix: banner image positions
  site/pages/index.less
Labels: PR: unreviewed, bug
