Repository antvis/antvis.github.io, pull requests merged in 2020-04, with the labels that each got.

#65 fix: G2Plot chart url update. fix: screenshot for percent stacked bar…
  site/data/chart-urls.json
Labels: PR: unreviewed, bug

#66 fix: principles visual image problem
  docs/specification/principles/visual.en.md
  docs/specification/principles/visual.zh.md
Labels: PR: unreviewed, bug

#67 fix: principle doc image problem
  docs/specification/principles/visual.en.md
  docs/specification/principles/visual.zh.md
Labels: PR: unreviewed, bug

#68 docs: Add color component to document
  README.md
  docs/specification/principles/basic.en.md
  docs/specification/principles/basic.zh.md
  docs/specification/principles/visual.en.md
  docs/specification/principles/visual.zh.md
  package.json
  site/components/ContributorCard/ContributorCard.tsx
  site/components/Contributors/Contributors.tsx
  site/components/DecisionTree/DecisionTree.tsx
  site/components/Products/Products.module.less
  site/components/Products/Products.tsx
  site/components/Resources/Resources.module.less
  site/components/Resources/Resources.tsx
  site/components/bannerSVG/bannerSVG.tsx
Labels: PR: unreviewed, documentation

#69 chore: 🔀 add GitHub Action to sync Gitee
  .github/workflows/mirror.yml
Labels: PR: unreviewed, chore
