Repository antvis/antvis.github.io, pull requests merged in 2020-03, with the labels that each got.

#56 fix: 按照设计师要求进行文案修改
  docs/specification/principles/visual.en.md
  docs/specification/principles/visual.zh.md
  docs/specification/resources.en.md
  docs/specification/resources.zh.md
Labels: PR: reviewed-changes-requested, bug

#58 fix: decision tree tooltip problem. feat: highlight the hovered tree …
  site/components/DecisionTree/DecisionTree.module.less
  site/components/DecisionTree/DecisionTree.tsx
Labels: PR: unreviewed, bug

#59 fix: decision tree shaking problem
  package.json
  site/components/DecisionTree/DecisionTree.tsx
Labels: PR: unreviewed, bug

#60 fix: fullscreen problem.
  site/components/DecisionTree/DecisionTree.tsx
Labels: PR: unreviewed, bug

#61 fix: light shaking
  site/components/DecisionTree/DecisionTree.tsx
Labels: PR: unreviewed, bug

#63 Graph hover style
  site/components/DecisionTree/DecisionTree.tsx
Labels: PR: unreviewed, enhancement

#64 fix: auto change the canvas when the graph size is changed. fix: hove…
  site/components/DecisionTree/DecisionTree.module.less
  site/components/DecisionTree/DecisionTree.tsx
  site/components/ResourceCard/ResourceCard.module.less
Labels: PR: unreviewed, bug
