Repository antvis/antvis.github.io, pull requests merged in 2020-12, with the labels that each got.

#105 feat: response sizes
  site/pages/d2.less
  site/pages/d2.zh.tsx
Labels: PR: reviewed-approved

#107 chore: update styles
  site/pages/d2.less
  site/pages/d2.zh.tsx
Labels: PR: reviewed-changes-requested

#108 fix: update sticker srcs
  site/pages/d2.less
  site/pages/d2.zh.tsx
Labels: PR: unreviewed

#109 fix: last button img
  site/pages/d2.zh.tsx
Labels: PR: reviewed-approved

#106 fix: body background color
  site/pages/d2.en.tsx
  site/pages/index.less
Labels: PR: unreviewed

#111 feat: qrcode for pad and pc
  site/pages/d2.less
  site/pages/d2.zh.tsx
Labels: PR: reviewed-changes-requested

#115 chore: update the bottom imgs and remove the lottery code
  site/pages/d2.zh.tsx
Labels: PR: unreviewed

#114 fix:update links for banner and design documents
  docs/specification/language/palette.zh.md
  docs/specification/principles/basic.en.md
  docs/specification/principles/basic.zh.md
  docs/specification/standby/antvColorList.en.md
  docs/specification/standby/antvColorList.zh.md
  package.json
  site/components/Banner/Banner.tsx
Labels: PR: unreviewed

#116 Update contributors: buming github link
  site/data/contributors.tsx
Labels: PR: unreviewed
