Repository antvis/antvis.github.io, pull requests merged in 2020-11, with the labels that each got.

#84 feat: 11.22样式更新
  site/components/Banner/Banner.module.less
  site/components/Banner/Banner.tsx
  site/components/Banner/play.svg
  site/components/DecisionTree/DecisionTree.module.less
  site/pages/index.zh.tsx
Labels: PR: unreviewed

#87 fix: surge preview in wrong ref
  .github/workflows/preview.yml
Labels: PR: unreviewed

#90 feat: 马赛克拼图功能
  package.json
  site/components/Banner/Banner.tsx
  site/components/DemoTwo/DemoTwo.js
  site/components/DemoTwo/DemoTwo.module.less
Labels: PR: reviewed-changes-requested

#91 Feat home explain
  .github/workflows/preview.yml
  docs/specification/components/axis.en.md
  docs/specification/components/axis.zh.md
  docs/specification/components/graphic.en.md
  docs/specification/components/graphic.zh.md
  docs/specification/components/label.en.md
  docs/specification/components/label.zh.md
  docs/specification/components/legend.en.md
  docs/specification/components/legend.zh.md
  docs/specification/components/titlenotes.zh.md
  docs/specification/components/tooltip.en.md
  docs/specification/components/tooltip.zh.md
  docs/specification/graph/card.zh.md
  docs/specification/graph/chart.zh.md
  docs/specification/graph/conDashboard.zh.md
  docs/specification/graph/map.zh.md
  docs/specification/graph/mobile.zh.md
  docs/specification/graph/pubDashboard.zh.md
  docs/specification/language/basic.en.md
  docs/specification/language/basic.zh.md
  docs/specification/language/interact.en.md
  docs/specification/language/interact.zh.md
  docs/specification/language/mobile.en.md
  docs/specification/language/mobile.zh.md
  docs/specification/language/visual.en.md
  docs/specification/language/visual.zh.md
  docs/specification/module/annotation.zh.md
  docs/specification/module/axis.zh.md
  docs/specification/module/axisNavigator.zh.md
  docs/specification/module/element.zh.md
  docs/specification/module/infoCom/infoComponents.zh.md
  docs/specification/module/infoCom/legend.zh.md
  docs/specification/module/infoCom/tooltip.zh.md
  docs/specification/module/label.zh.md
  docs/specification/module/timeBar.zh.md
  docs/specification/module/titleNote.zh.md
  docs/specification/module/viewToolBar.zh.md
  docs/specification/principles.en.md
  docs/specification/principles.zh.md
  docs/specification/resources.zh.md
  docs/specification/standby/antvColorList.zh.md
  docs/specification/strategy/analysis.zh.md
  docs/specification/strategy/modal.en.md
  docs/specification/strategy/modal.zh.md
  docs/specification/tool/createrColor.zh.md
  gatsby-config.js
Labels: PR: unreviewed

#94 feat:修改组件设计指引模块图片
  docs/specification/module/annotation.zh.md
  docs/specification/module/axisNavigator.zh.md
  docs/specification/module/element.zh.md
  docs/specification/module/infoCom/infoComponents.zh.md
  docs/specification/module/infoCom/legend.zh.md
  docs/specification/module/infoCom/tooltip.zh.md
  docs/specification/module/label.zh.md
  docs/specification/module/timeBar.zh.md
  docs/specification/module/viewToolBar.zh.md
  docs/specification/tool/createrColor.zh.md
  gatsby-config.js
Labels: PR: unreviewed

#96 feat: 首页about添加站点入口
  site/components/Banner/Banner.module.less
  site/components/Banner/Banner.tsx
  site/data/banner-link.json
Labels: PR: unreviewed

#97 fix: delete br
  docs/specification/graph/card.en.md
  docs/specification/graph/card.zh.md
  docs/specification/graph/chart.en.md
  docs/specification/graph/chart.zh.md
  docs/specification/graph/conDashboard.en.md
  docs/specification/graph/conDashboard.zh.md
  docs/specification/graph/graph.zh.md
  docs/specification/graph/map.en.md
  docs/specification/graph/map.zh.md
  docs/specification/graph/mobile.en.md
  docs/specification/graph/mobile.zh.md
  docs/specification/graph/pubDashboard.en.md
  docs/specification/graph/pubDashboard.zh.md
  docs/specification/language/basic.en.md
  docs/specification/language/basic.zh.md
  docs/specification/language/interact.en.md
  docs/specification/language/interact.zh.md
  docs/specification/language/media.en.md
  docs/specification/language/media.zh.md
  docs/specification/language/palette.zh.md
  docs/specification/module/annotation.en.md
  docs/specification/module/annotation.zh.md
  docs/specification/module/axis.en.md
  docs/specification/module/axis.zh.md
  docs/specification/module/axisNavigator.en.md
  docs/specification/module/axisNavigator.zh.md
  docs/specification/module/element.en.md
  docs/specification/module/element.zh.md
  docs/specification/module/info.zh.md
  docs/specification/module/infoCom/infoComponents.en.md
  docs/specification/module/infoCom/infoComponents.zh.md
  docs/specification/module/infoCom/legend.en.md
  docs/specification/module/infoCom/legend.zh.md
  docs/specification/module/infoCom/tooltip.en.md
  docs/specification/module/infoCom/tooltip.zh.md
  docs/specification/module/label.en.md
  docs/specification/module/label.zh.md
  docs/specification/module/timeBar.en.md
  docs/specification/module/timeBar.zh.md
  docs/specification/module/titleNote.en.md
  docs/specification/module/titleNote.zh.md
  docs/specification/module/viewToolBar.en.md
  docs/specification/module/viewToolBar.zh.md
  docs/specification/principles.en.md
  docs/specification/principles.zh.md
  docs/specification/strategy/analysis.en.md
  docs/specification/strategy/analysis.zh.md
  docs/specification/strategy/modal.en.md
  docs/specification/strategy/modal.zh.md
  docs/specification/tool/createrColor.en.md
  docs/specification/tool/createrColor.zh.md
Labels: PR: unreviewed

#98 fix: update demo info
  site/components/Demos/Demos.tsx
  site/data/banner-info.json
Labels: PR: reviewed-approved
